spring.application.name=job-board

spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:34967/railway
spring.datasource.username=root
spring.datasource.password=RSwuUUCGkeFylDTMyINNNiTcPHVkUAlZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080